//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSIPPAI.Clases.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleExposicionPersistente
    {
        public string lugarAsignado { get; set; }
        public int idObra { get; set; }
        public int idExposicion { get; set; }
    
        public virtual ObraPersistente ObraPersistente { get; set; }
        public virtual ExposicionPersistente ExposicionPersistente { get; set; }
    }
}
