//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSIPPAI.Clases.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoPersistente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpleadoPersistente()
        {
            this.ExposicionPersistente = new HashSet<ExposicionPersistente>();
            this.ObraPersistente = new HashSet<ObraPersistente>();
            this.UsuarioPersistente = new HashSet<UsuarioPersistente>();
        }
    
        public string apellido { get; set; }
        public int codigoValidacion { get; set; }
        public long cuit { get; set; }
        public int dni { get; set; }
        public string domicili { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string correo { get; set; }
        public string nombre { get; set; }
        public string sexo { get; set; }
        public int idSede { get; set; }
        public int idEmpleado { get; set; }
    
        public virtual SedePersistente SedePersistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExposicionPersistente> ExposicionPersistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObraPersistente> ObraPersistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioPersistente> UsuarioPersistente { get; set; }
    }
}
