//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSIPPAI.Clases.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaPersistente
    {
        public int idEntrada { get; set; }
        public int monto { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public System.TimeSpan horaVenta { get; set; }
        public int idSede { get; set; }
        public int idTarifa { get; set; }
    
        public virtual SedePersistente SedePersistente { get; set; }
        public virtual TarifaPersistente TarifaPersistente { get; set; }
    }
}
