//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSIPPAI.Clases.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExposicionPersistente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExposicionPersistente()
        {
            this.DetalleExposicionPersistente = new HashSet<DetalleExposicionPersistente>();
            this.SedePersistente = new HashSet<SedePersistente>();
        }
    
        public int idExposicion { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaFin { get; set; }
        public Nullable<System.DateTime> fechaFinReplanificada { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaInicioReplanificada { get; set; }
        public System.TimeSpan horaApertura { get; set; }
        public System.TimeSpan horaCierre { get; set; }
        public int idEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleExposicionPersistente> DetalleExposicionPersistente { get; set; }
        public virtual EmpleadoPersistente EmpleadoPersistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SedePersistente> SedePersistente { get; set; }
    }
}
