//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSIPPAI.Clases.Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSI_PPAI_G1Entities4 : DbContext
    {
        public DSI_PPAI_G1Entities4()
            : base("name=DSI_PPAI_G1Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetalleExposicionPersistente> DetalleExposicionPersistente { get; set; }
        public virtual DbSet<EmpleadoPersistente> EmpleadoPersistente { get; set; }
        public virtual DbSet<EntradaPersistente> EntradaPersistente { get; set; }
        public virtual DbSet<ExposicionPersistente> ExposicionPersistente { get; set; }
        public virtual DbSet<ObraPersistente> ObraPersistente { get; set; }
        public virtual DbSet<ReservaVisitaPersistente> ReservaVisitaPersistente { get; set; }
        public virtual DbSet<SedePersistente> SedePersistente { get; set; }
        public virtual DbSet<SesionPersistente> SesionPersistente { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TarifaPersistente> TarifaPersistente { get; set; }
        public virtual DbSet<TipoDeEntradaPersistente> TipoDeEntradaPersistente { get; set; }
        public virtual DbSet<TipoVisitaPersistente> TipoVisitaPersistente { get; set; }
        public virtual DbSet<UsuarioPersistente> UsuarioPersistente { get; set; }
    }
}
