//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSIPPAI.Clases.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObraPersistente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObraPersistente()
        {
            this.DetalleExposicionPersistente = new HashSet<DetalleExposicionPersistente>();
        }
    
        public int codigoSensor { get; set; }
        public double alto { get; set; }
        public double ancho { get; set; }
        public string descripcion { get; set; }
        public int duracionExtendida { get; set; }
        public int duracionResumida { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaPrimerIngreso { get; set; }
        public string nombreObra { get; set; }
        public double peso { get; set; }
        public double valuacion { get; set; }
        public int idEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleExposicionPersistente> DetalleExposicionPersistente { get; set; }
        public virtual EmpleadoPersistente EmpleadoPersistente { get; set; }
    }
}
