//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSIPPAI.Clases.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaVisitaPersistente
    {
        public int cantidadAlumnos { get; set; }
        public Nullable<int> cantidadAlumnosConfirmada { get; set; }
        public Nullable<int> duracionEstimada { get; set; }
        public System.DateTime fechaHoraCreacion { get; set; }
        public System.DateTime fechaHoraReserva { get; set; }
        public Nullable<System.TimeSpan> horaFinReal { get; set; }
        public Nullable<System.TimeSpan> horaInicioReal { get; set; }
        public int idReservaVisita { get; set; }
        public int idSede { get; set; }
    
        public virtual SedePersistente SedePersistente { get; set; }
    }
}
