//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSIPPAI.Clases.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifaPersistente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TarifaPersistente()
        {
            this.EntradaPersistente = new HashSet<EntradaPersistente>();
            this.SedePersistente = new HashSet<SedePersistente>();
        }
    
        public int idTarifa { get; set; }
        public System.DateTime fechaFinVigencia { get; set; }
        public System.DateTime fechaInicioVigencia { get; set; }
        public int monto { get; set; }
        public int montoAdicionalGuia { get; set; }
        public int idTipoDeEntrada { get; set; }
        public int idTipoVisita { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntradaPersistente> EntradaPersistente { get; set; }
        public virtual TipoDeEntradaPersistente TipoDeEntradaPersistente { get; set; }
        public virtual TipoVisitaPersistente TipoVisitaPersistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SedePersistente> SedePersistente { get; set; }
    }
}
