//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSIPPAI.Clases.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeEntradaPersistente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoDeEntradaPersistente()
        {
            this.TarifaPersistente = new HashSet<TarifaPersistente>();
        }
    
        public string nombre { get; set; }
        public int idTipoDeEntrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifaPersistente> TarifaPersistente { get; set; }
    }
}
